version: "3.8"

services:
  ghidra-server:
    build:
      context: .
    network_mode: "host"
    volumes:
      - repos:/ghidra/repos
      - ./server.conf:/ghidra/server/server.conf
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx4g

volumes:
  repos:
